resolver: nightly-2019-05-11

flags:
  Taiji-ATAC-seq:
    exe: true

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  af37677ff940cd2b50090e7921b0bf8365e45fda

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  75a8a813410a5c8267a59794c875f4d277ceb1be
  subdirs: 
    - bioinformatics-toolkit

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  3b756e3ff0cb31c4e9ed8a1cc8d24c2ea6951af6

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  5fd7472babf427606058594c089abf689b7b89f4

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- drmaa-0.2.0
- clustering-0.4.1
- SciFlow-0.6.2